# Generated by Django 3.1.4 on 2021-01-15 13:42

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.CharField(db_index=True, default=common.utils.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('trash', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
